### ISSUE TITLE
install_ffmpeg.sh uninstalls gcc, bzip2, etc.

### ISSUE THREAD

**Issue by jleni** [mbartoli/neural-animation#1]
Thanks Mike for putting this together! 
The only small complaint I have is that using install_ffmpeg uninstalls gcc, etc.. Maybe you should detect if any of those packages were there before and avoid uninstalling them.

**Comment by philipperemy** [comment]
```
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg
```

will work. Trust me 👍
