### ISSUE TITLE
directory issues

### ISSUE THREAD

**Issue by sunmkim** [mbartoli/neural-animation#2]
Hi, I'm trying to use this to paint a new video via gif (paint.py), but I was wondering if I can get an example of the pathway/directory that you use. For some reason, it doesn't recognize `./example.gif` when i use a relative path for the `example.gif` that is in the same folder as `neural-animation`. Thanks!

**Comment by philipperemy** [comment]
Try this

```
./movie2frames.sh ffmpeg sample/processed.gif frames jpg
python paint.py -i frames -o output_frames -s sample/The_Scream.jpg
```
