### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by reillydonovan** [mbartoli/neural-animation#3]
While running, it starts and returns:

Processing frame #60
Couldn't load models/VGG_ILSVRC_19_layers.caffemodel
/home/ubuntu/torch/install/bin/luajit: neural_style.lua:51: attempt to index a nil value
stack traceback:
    neural_style.lua:51: in function 'main'
    neural_style.lua:350: in main chunk
    [C]: in function 'dofile'
    ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
    [C]: at 0x00406670

any suggestions on how to get this to work?  I can get neural-style to work with gpu just not neural-animation

**Comment by philipperemy** [comment]
It means you have to run the `download_models.sh` script in `models`

**Comment by philipperemy** [comment]
```
cd models
chmod +x download_models.sh
./download_models.sh
```

will solve your problem
