### ISSUE TITLE
Couple of quick questions

### ISSUE THREAD

**Issue by jcklpe** [mbartoli/neural-animation#5]
Hey, artist/designer here. I've already got JcJohnson's neural style running on a linux dual boot, but was wondering how to integrate this video stuff into it? I'm just an artist/designer so I'm not really as up on the code stuff as maybe I should be, and I'm not quite sure where to begin. Looks like the only dependency I'm lacking is ffmpeg.

**Comment by philipperemy** [comment]
```
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg
```

works on ubuntu
